const contributors = [
  {
    name: "Dr. Michael Dietze",
    email: "dietze@bu.edu",
    role: "PEcAn Lead PI",
    profession: "Professor, Boston University",
    img: "http://people.bu.edu/dietze/images/MikePalEON.jpg",
  },
  {
    name: "Dr. David LeBauer",
    email: "dlebauer@gmail.com",
    role: "PEcAn Co-PI",
    profession: "Scientist, The LeBauer Approach LLC and University of Arizona",
    img: "https://datascience.cct.arizona.edu/sites/default/files/styles/az_medium/public/2023-11/david_lebauer.jpeg.webp",
  },
  {
    name: "Dr. Kenton McHenry",
    email: "mchenry@illinois.edu",
    role: "PEcAn Co-PI",
    profession: "Research Assistant Professor, University of Illinois",
    img: "https://ws.engr.illinois.edu/directory/viewphoto.aspx?photo=16479&s=300",
  },
  {
    name: "Dr. Ankur Desai",
    email: "desai@aos.wisc.edu",
    role: "PEcAn Co-PI",
    profession: "Department Chair, Professor, University of Wisconsin",
    img: "https://aos.wisc.edu/images/people/Desai_2022.jpg",
  },
  {
    name: "Rob Kooper",
    email: "kooper@illinois.edu",
    role: "",
    profession: "Lead Research Soft Engineer, University of Illinois",
    img: "https://internal.ncsa.illinois.edu/mis/user/public/photoForUser.php?login=kooper",
  },
  {
    name: "Shawn Serbin",
    email: "shawn.p.serbin@nasa.gov",
    role: "",
    profession: "Supervisory Research AST Earth Science Remote Sensing, NASA Goddard Space Flight Center",
    img: "https://ngee-tropics.lbl.gov/wp-content/uploads/sites/16/2017/01/Shawn-Serbin.jpg",
  },
  {
    name: "Christopher Black",
    email: "chris@ckblack.org",
    role: "",
    profession: "Scientist, Pools and Fluxes LLC",
    img: "https://ckblack.org/2014/04/ckb-20140427-300px.jpg",
  },
  {
    name: "Istem Fer",
    email: "fer.istem@gmail.com",
    role: "",
    profession: "Senior researcher, Finnish Meteorological Institute",
    img: "https://people.bu.edu/dietze/images/ifp_photo-426x636.jpg",
  },
  {
    name: "Alexey Shiklomanov",
    email: "alexey.shiklomanov@nasa.gov",
    role: "",
    profession: "Research physical scientist, NASA",
    img: "https://science.gsfc.nasa.gov/sed/images/Photos/98337/442020141030_magnolia-small.jpg",
  },
  {
    name: "Dr. Betsy Cowdery",
    email: "",
    role: "",
    profession: "Postdoctoral Researcher, The James Hutton Institute",
    img: "https://people.bu.edu/dietze/images/04-elizabeth.jpg",
  },
  {
    name: "Dongchen Zhang",
    email: "zhangdc@bu.edu", 
    role: "PhD Student",
    profession: "PhD Student in Dr. Michael Dietze's Lab, Boston University",
    img: "https://people.bu.edu/dietze/images/Dongchen.jpg", 
  },
  {
    name: "Qianyu Li",
    email: "qli1@bnl.gov", 
    role: "Research Scientist",
    profession: "Brookhaven National Lab",
    img: "https://www.bnl.gov/assets/global/images/render.php?q=0|26462.jpg|500", 
  },
  {
    name: "Meet Agarwal",
    email: "agrawalmeet91@gmail.com",
    role: "GSoC'23 Contributor",
    profession: "Software Engineer",
    img: "https://64.media.tumblr.com/c8143e590d0312d730d5dd42e345126a/e1e32936de328bec-90/s1280x1920/8e05bb187c1458f41f0c341ddb8f91d5e228ed77.jpg",
  },
  {
    name: "Nihar Sanda",
    email: "nihar.sanda@gmail.com",
    role: "GSoC'22 & GSoC'23 Contributor; GSoC '24 Mentor",
    profession: "Research Associate, IIT Bombay",
    img: "https://koolgax99.github.io/nihar.jpg",
  },
];
export default contributors;
